import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest';

const requireProtectedApiSessionValueMock = vi.fn();
const fakePlaylistServices = {
  addVideoToPlaylist: { execute: vi.fn() },
  createPlaylist: { execute: vi.fn() },
  deletePlaylist: { execute: vi.fn() },
  findPlaylists: { execute: vi.fn() },
  getPlaylistDetails: { execute: vi.fn() },
  removeVideoFromPlaylist: { execute: vi.fn() },
  reorderPlaylistItems: { execute: vi.fn() },
  updatePlaylist: { execute: vi.fn() },
};

async function importPlaylistsApiRoute() {
  return import('../../../app/routes/api.playlists');
}

async function importPlaylistDetailApiRoute() {
  return import('../../../app/routes/api.playlists.$id');
}

async function importPlaylistItemsApiRoute() {
  return import('../../../app/routes/api.playlists.$id.items');
}

async function importPlaylistItemApiRoute() {
  return import('../../../app/routes/api.playlists.$id.items.$videoId');
}

describe('playlist API owner boundary contract', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.clearAllMocks();
    vi.doMock('~/composition/server/auth', () => ({
      requireProtectedApiSessionValue: requireProtectedApiSessionValueMock,
    }));
    vi.doMock('~/composition/server/playlist', () => ({
      getServerPlaylistServices: () => fakePlaylistServices,
    }));
    requireProtectedApiSessionValueMock.mockResolvedValue({ id: 'session-1', userId: 'owner-1' });
  });

  afterEach(() => {
    vi.doUnmock('~/composition/server/auth');
    vi.doUnmock('~/composition/server/playlist');
    vi.resetModules();
  });

  test('update route ignores owner identity from request JSON', async () => {
    fakePlaylistServices.updatePlaylist.execute.mockResolvedValue({
      data: { fieldsUpdated: ['name'], message: 'updated', playlist: { id: 'playlist-1', name: 'Vault', ownerId: 'owner-1' } },
      success: true,
    });
    const { action } = await importPlaylistDetailApiRoute();

    const response = await action({
      params: { id: 'playlist-1' },
      request: new Request('http://localhost/api/playlists/playlist-1', {
        body: JSON.stringify({ name: 'Vault', ownerId: 'attacker-owner' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'PUT',
      }),
    } as never);

    expect(fakePlaylistServices.updatePlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({
      name: 'Vault',
      ownerId: 'owner-1',
      playlistId: 'playlist-1',
    }));
    expect(response.status).toBe(200);
  });

  test('mutation routes pass authenticated owner identity to playlist services', async () => {
    fakePlaylistServices.createPlaylist.execute.mockResolvedValue({
      data: { autoGeneratedThumbnail: false, message: 'created', playlistId: 'playlist-1' },
      success: true,
    });
    fakePlaylistServices.deletePlaylist.execute.mockResolvedValue({
      data: { deletedPlaylistName: 'Vault', message: 'deleted', relatedPlaylistsAffected: [], success: true, videosAffected: 0 },
      success: true,
    });
    fakePlaylistServices.addVideoToPlaylist.execute.mockResolvedValue({
      data: { finalPosition: 0, message: 'added', playlistName: 'Vault', success: true, totalVideosInPlaylist: 1, videoTitle: 'Video' },
      success: true,
    });
    fakePlaylistServices.reorderPlaylistItems.execute.mockResolvedValue({
      data: { message: 'reordered', newOrder: ['video-2', 'video-1'], oldOrder: ['video-1', 'video-2'], playlistName: 'Vault', success: true, videosReordered: 2 },
      success: true,
    });
    fakePlaylistServices.removeVideoFromPlaylist.execute.mockResolvedValue({
      data: { message: 'removed', playlistId: 'playlist-1', remainingVideos: 1, success: true, videoId: 'video-1' },
      success: true,
    });

    const { action: createAction } = await importPlaylistsApiRoute();
    await createAction({
      request: new Request('http://localhost/api/playlists', {
        body: JSON.stringify({ name: 'Vault', type: 'user_created' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'POST',
      }),
    } as never);

    const { action: detailAction } = await importPlaylistDetailApiRoute();
    await detailAction({ params: { id: 'playlist-1' }, request: new Request('http://localhost/api/playlists/playlist-1', { method: 'DELETE' }) } as never);

    const { action: itemsAction } = await importPlaylistItemsApiRoute();
    await itemsAction({
      params: { id: 'playlist-1' },
      request: new Request('http://localhost/api/playlists/playlist-1/items', {
        body: JSON.stringify({ videoId: 'video-1' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'POST',
      }),
    } as never);
    await itemsAction({
      params: { id: 'playlist-1' },
      request: new Request('http://localhost/api/playlists/playlist-1/items', {
        body: JSON.stringify({ newOrder: ['video-2', 'video-1'] }),
        headers: { 'Content-Type': 'application/json' },
        method: 'PUT',
      }),
    } as never);

    const { action: itemAction } = await importPlaylistItemApiRoute();
    await itemAction({ params: { id: 'playlist-1', videoId: 'video-1' }, request: new Request('http://localhost/api/playlists/playlist-1/items/video-1', { method: 'DELETE' }) } as never);

    expect(fakePlaylistServices.createPlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({ ownerId: 'owner-1' }));
    expect(fakePlaylistServices.deletePlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({ ownerId: 'owner-1' }));
    expect(fakePlaylistServices.addVideoToPlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({ ownerId: 'owner-1' }));
    expect(fakePlaylistServices.reorderPlaylistItems.execute).toHaveBeenCalledWith(expect.objectContaining({ ownerId: 'owner-1' }));
    expect(fakePlaylistServices.removeVideoFromPlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({ ownerId: 'owner-1' }));
  });

  test('mutation routes return auth responses before touching services', async () => {
    requireProtectedApiSessionValueMock.mockResolvedValue(new Response('unauthorized', { status: 401 }));
    const { action } = await importPlaylistDetailApiRoute();

    const response = await action({
      params: { id: 'playlist-1' },
      request: new Request('http://localhost/api/playlists/playlist-1', {
        body: JSON.stringify({ name: 'Vault' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'PUT',
      }),
    } as never);

    expect(response.status).toBe(401);
    await expect(response.text()).resolves.toBe('unauthorized');
    expect(fakePlaylistServices.updatePlaylist.execute).not.toHaveBeenCalled();
    expect(fakePlaylistServices.deletePlaylist.execute).not.toHaveBeenCalled();
  });
});
