import { describe, expect, test, vi } from 'vitest';
import { CreatePlaylistUseCase } from './create-playlist.usecase';

describe('CreatePlaylistUseCase', () => {
  test('returns a duplicate-name failure when the owner already has a playlist with the same name', async () => {
    const nameExistsForOwner = vi.fn(async () => true);
    const create = vi.fn();
    const useCase = new CreatePlaylistUseCase({
      playlistRepository: {
        create,
        nameExistsForOwner,
      },
      videoCatalog: {
        findById: vi.fn(),
      },
    });

    await expect(useCase.execute({
      name: 'Vault',
      ownerId: 'owner-1',
      type: 'user_created',
    })).resolves.toEqual({
      message: 'Playlist with name "Vault" already exists for user "owner-1"',
      ok: false,
      reason: 'DUPLICATE_PLAYLIST_NAME',
    });

    expect(nameExistsForOwner).toHaveBeenCalledWith('Vault', 'owner-1');
    expect(create).not.toHaveBeenCalled();
  });

  test('creates a playlist, trims inputs, and returns suggested metadata when needed', async () => {
    const create = vi.fn(async input => ({
      createdAt: new Date('2026-03-08T00:00:00.000Z'),
      description: input.description,
      id: 'playlist-1',
      isPublic: input.isPublic,
      metadata: input.metadata,
      name: input.name,
      ownerId: input.ownerId,
      type: input.type,
      updatedAt: new Date('2026-03-08T00:00:00.000Z'),
      videoIds: input.videoIds ?? [],
    }));
    const useCase = new CreatePlaylistUseCase({
      playlistRepository: {
        create,
        nameExistsForOwner: vi.fn(async () => false),
      },
      videoCatalog: {
        findById: vi.fn(async videoId => ({
          duration: 60,
          id: videoId,
          title: videoId,
        })),
      },
    });

    await expect(useCase.execute({
      description: '  Stored description  ',
      initialVideoIds: ['video-1'],
      name: '  Vault Saga  ',
      ownerId: 'owner-1',
      type: 'series',
      metadata: {
        seriesName: 'Vault Saga',
      },
    })).resolves.toEqual({
      ok: true,
      data: {
        autoGeneratedThumbnail: false,
        message: 'Playlist "Vault Saga" created successfully',
        playlistId: 'playlist-1',
        suggestedMetadata: expect.objectContaining({
          status: 'ongoing',
          year: expect.any(Number),
        }),
      },
    });

    expect(create).toHaveBeenCalledWith({
      description: 'Stored description',
      isPublic: false,
      metadata: {
        seriesName: 'Vault Saga',
      },
      name: 'Vault Saga',
      ownerId: 'owner-1',
      type: 'series',
      videoIds: ['video-1'],
    });
  });

  test('rejects initial videos that are not accessible to the playlist owner', async () => {
    const create = vi.fn();
    const findById = vi.fn(async () => null);
    const useCase = new CreatePlaylistUseCase({
      playlistRepository: {
        create,
        nameExistsForOwner: vi.fn(async () => false),
      },
      videoCatalog: {
        findById,
      },
    });

    await expect(useCase.execute({
      initialVideoIds: ['other-private-video'],
      name: 'Vault',
      ownerId: 'owner-1',
      type: 'user_created',
    })).resolves.toEqual({
      message: 'Video with ID "other-private-video" not found',
      ok: false,
      reason: 'VIDEO_NOT_FOUND',
    });
    expect(findById).toHaveBeenCalledWith('other-private-video', {
      ownerId: 'owner-1',
      type: 'public_or_owned',
    });
    expect(create).not.toHaveBeenCalled();
  });
});
