import { createVideoReadAccessScope } from '~/modules/library/application/policies/video-read-access-scope';
import type { CreatePlaylistRequest, PlaylistMetadata } from '../../domain/playlist';
import type { PlaylistRepositoryPort } from '../ports/playlist-repository.port';
import type { PlaylistVideoCatalogPort } from '../ports/playlist-video-catalog.port';

export interface CreatePlaylistInput extends CreatePlaylistRequest {
  ownerId: string;
}

export interface CreatePlaylistOutput {
  autoGeneratedThumbnail: false;
  message: string;
  playlistId: string;
  suggestedMetadata?: Partial<PlaylistMetadata>;
}

export type CreatePlaylistUseCaseResult =
  | {
    ok: true;
    data: CreatePlaylistOutput;
  }
  | {
    ok: false;
    message: string;
    reason:
      | 'DUPLICATE_PLAYLIST_NAME'
      | 'INVALID_PLAYLIST_DATA'
      | 'INVALID_SERIES_METADATA'
      | 'PLAYLIST_MUTATION_FAILED'
      | 'VIDEO_NOT_FOUND';
  };

interface CreatePlaylistUseCaseDependencies {
  playlistRepository: Pick<PlaylistRepositoryPort, 'create' | 'nameExistsForOwner'>;
  videoCatalog: Pick<PlaylistVideoCatalogPort, 'findById'>;
}

function getSuggestedMetadata(input: CreatePlaylistRequest) {
  if (input.type === 'user_created') {
    return undefined;
  }

  const suggestions: Partial<PlaylistMetadata> = {};

  if (input.type === 'series' && !input.metadata?.status) {
    suggestions.status = 'ongoing';
  }

  if (!input.metadata?.year) {
    suggestions.year = new Date().getFullYear();
  }

  return Object.keys(suggestions).length > 0 ? suggestions : undefined;
}

function validateCreateRequest(input: CreatePlaylistRequest): CreatePlaylistUseCaseResult | null {
  if (!input.name?.trim() || !input.type) {
    return {
      message: 'Playlist name and type are required',
      ok: false,
      reason: 'INVALID_PLAYLIST_DATA',
    };
  }

  if (input.name.trim().length > 255) {
    return {
      message: 'Invalid playlist name: cannot exceed 255 characters',
      ok: false,
      reason: 'INVALID_PLAYLIST_DATA',
    };
  }

  if (input.description && input.description.trim().length > 1000) {
    return {
      message: 'Invalid playlist description: cannot exceed 1000 characters',
      ok: false,
      reason: 'INVALID_PLAYLIST_DATA',
    };
  }

  if ((input.type === 'series' || input.type === 'season') && !input.metadata?.seriesName) {
    return {
      message: 'Invalid series metadata: seriesName is required for series and season playlists',
      ok: false,
      reason: 'INVALID_SERIES_METADATA',
    };
  }

  if (input.type === 'season' && (!input.metadata?.seasonNumber || input.metadata.seasonNumber < 1)) {
    return {
      message: 'Invalid series metadata: seasonNumber must be a positive integer for season playlists',
      ok: false,
      reason: 'INVALID_SERIES_METADATA',
    };
  }

  return null;
}

export class CreatePlaylistUseCase {
  constructor(
    private readonly deps: CreatePlaylistUseCaseDependencies,
  ) {}

  async execute(input: CreatePlaylistInput): Promise<CreatePlaylistUseCaseResult> {
    const validationFailure = validateCreateRequest(input);
    if (validationFailure) {
      return validationFailure;
    }

    try {
      const name = input.name.trim();
      const nameExists = await this.deps.playlistRepository.nameExistsForOwner(name, input.ownerId);

      if (nameExists) {
        return {
          message: `Playlist with name "${name}" already exists for user "${input.ownerId}"`,
          ok: false,
          reason: 'DUPLICATE_PLAYLIST_NAME',
        };
      }

      const initialVideoIds = input.initialVideoIds ?? [];
      const readScope = createVideoReadAccessScope({
        type: 'authenticated',
        userId: input.ownerId,
      });

      for (const videoId of initialVideoIds) {
        const video = await this.deps.videoCatalog.findById(videoId, readScope);

        if (!video) {
          return {
            message: `Video with ID "${videoId}" not found`,
            ok: false,
            reason: 'VIDEO_NOT_FOUND',
          };
        }
      }

      const playlist = await this.deps.playlistRepository.create({
        description: input.description?.trim() || undefined,
        isPublic: input.isPublic ?? false,
        metadata: input.metadata,
        name,
        ownerId: input.ownerId,
        type: input.type,
        videoIds: initialVideoIds,
      });

      return {
        ok: true,
        data: {
          autoGeneratedThumbnail: false,
          message: `Playlist "${playlist.name}" created successfully`,
          playlistId: playlist.id,
          suggestedMetadata: getSuggestedMetadata(input),
        },
      };
    }
    catch {
      return {
        message: 'Failed to create playlist',
        ok: false,
        reason: 'PLAYLIST_MUTATION_FAILED',
      };
    }
  }
}
