// generated by react-router-hono-server/dev
import { createHonoServer } from 'react-router-hono-server/bun';
import { assertProductionStartupPreflight } from './composition/server/runtime-readiness';

await assertProductionStartupPreflight();

export default await createHonoServer();
