import type { PlaylistRepositoryPort } from '~/modules/playlist/application/ports/playlist-repository.port';
import type { PlaylistVideoCatalogPort } from '~/modules/playlist/application/ports/playlist-video-catalog.port';
import type {
  AddVideoToPlaylistUseCaseResult,
} from '~/modules/playlist/application/use-cases/add-video-to-playlist.usecase';
import type {
  CreatePlaylistUseCaseResult,
} from '~/modules/playlist/application/use-cases/create-playlist.usecase';
import type {
  DeletePlaylistUseCaseResult,
} from '~/modules/playlist/application/use-cases/delete-playlist.usecase';
import type {
  FindPlaylistsInput,
  FindPlaylistsOutput,
  FindPlaylistsUseCaseResult,
} from '~/modules/playlist/application/use-cases/find-playlists.usecase';
import type {
  GetPlaylistDetailsInput,
  GetPlaylistDetailsOutput,
  GetPlaylistDetailsUseCaseResult,
} from '~/modules/playlist/application/use-cases/get-playlist-details.usecase';
import type {
  RemoveVideoFromPlaylistUseCaseResult,
} from '~/modules/playlist/application/use-cases/remove-video-from-playlist.usecase';
import type {
  ReorderPlaylistItemsUseCaseResult,
} from '~/modules/playlist/application/use-cases/reorder-playlist-items.usecase';
import type {
  UpdatePlaylistUseCaseResult,
} from '~/modules/playlist/application/use-cases/update-playlist.usecase';
import type {
  CreatePlaylistRequest,
  Playlist,
  PlaylistMetadata,
  UpdatePlaylistRequest,
} from '~/modules/playlist/domain/playlist';
import { AddVideoToPlaylistUseCase } from '~/modules/playlist/application/use-cases/add-video-to-playlist.usecase';
import { CreatePlaylistUseCase } from '~/modules/playlist/application/use-cases/create-playlist.usecase';
import { DeletePlaylistUseCase } from '~/modules/playlist/application/use-cases/delete-playlist.usecase';
import { FindPlaylistsUseCase } from '~/modules/playlist/application/use-cases/find-playlists.usecase';
import { GetPlaylistDetailsUseCase } from '~/modules/playlist/application/use-cases/get-playlist-details.usecase';
import { RemoveVideoFromPlaylistUseCase } from '~/modules/playlist/application/use-cases/remove-video-from-playlist.usecase';
import { ReorderPlaylistItemsUseCase } from '~/modules/playlist/application/use-cases/reorder-playlist-items.usecase';
import { UpdatePlaylistUseCase } from '~/modules/playlist/application/use-cases/update-playlist.usecase';
import { SqlitePlaylistRepository } from '~/modules/playlist/infrastructure/sqlite/sqlite-playlist.repository';
import { SqlitePlaylistVideoCatalog } from '~/modules/playlist/infrastructure/video/sqlite-playlist-video-catalog.adapter';

export type PlaylistFailure = {
  error: string;
  success: false;
  reason: string;
  status: number;
};

export type PlaylistSuccess<T> = {
  data: T;
  success: true;
};

export type PlaylistResult<T> = PlaylistFailure | PlaylistSuccess<T>;

function ok<T>(data: T): PlaylistSuccess<T> {
  return { data, success: true };
}

function fail(reason: string, error: string, status: number): PlaylistFailure {
  return { error, reason, status, success: false };
}

function withSuccessFlag<T extends object>(data: T): T & { success: true } {
  return {
    ...data,
    success: true,
  };
}

interface ServerPlaylistServiceDependencies {
  playlistRepository: PlaylistRepositoryPort;
  videoCatalog: PlaylistVideoCatalogPort;
}

export interface ServerPlaylistServices {
  addVideoToPlaylist: {
    execute: (input: {
      episodeMetadata?: Record<string, unknown>;
      ownerId: string;
      playlistId: string;
      position?: number;
      videoId: string;
    }) => Promise<PlaylistResult<{
      finalPosition: number;
      message: string;
      playlistName: string;
      success: true;
      totalVideosInPlaylist: number;
      videoTitle: string;
    }>>;
  };
  createPlaylist: {
    execute: (input: CreatePlaylistRequest & { ownerId: string }) => Promise<PlaylistResult<{
      autoGeneratedThumbnail: false;
      message: string;
      playlistId: string;
      suggestedMetadata?: Partial<PlaylistMetadata>;
    }>>;
  };
  deletePlaylist: {
    execute: (input: {
      force?: boolean;
      ownerId: string;
      playlistId: string;
    }) => Promise<PlaylistResult<{
      deletedPlaylistName: string;
      message: string;
      relatedPlaylistsAffected: string[];
      success: true;
      videosAffected: number;
    }>>;
  };
  findPlaylists: {
    execute: (input: FindPlaylistsInput) => Promise<PlaylistResult<FindPlaylistsOutput>>;
  };
  getPlaylistDetails: {
    execute: (input: GetPlaylistDetailsInput) => Promise<PlaylistResult<GetPlaylistDetailsOutput>>;
  };
  removeVideoFromPlaylist: {
    execute: (input: {
      ownerId: string;
      playlistId: string;
      videoId: string;
    }) => Promise<PlaylistResult<{
      message: string;
      playlistId: string;
      remainingVideos: number;
      success: true;
      videoId: string;
    }>>;
  };
  reorderPlaylistItems: {
    execute: (input: {
      newOrder: string[];
      ownerId: string;
      playlistId: string;
      preserveMetadata?: boolean;
    }) => Promise<PlaylistResult<{
      message: string;
      newOrder: string[];
      oldOrder: string[];
      playlistName: string;
      success: true;
      videosReordered: number;
    }>>;
  };
  updatePlaylist: {
    execute: (input: UpdatePlaylistRequest & {
      ownerId: string;
      playlistId: string;
    }) => Promise<PlaylistResult<{
      fieldsUpdated: string[];
      message: string;
      playlist: Playlist;
    }>>;
  };
}

function resolveDependencies(
  overrides: Partial<ServerPlaylistServiceDependencies>,
): ServerPlaylistServiceDependencies {
  return {
    playlistRepository: overrides.playlistRepository ?? new SqlitePlaylistRepository(),
    videoCatalog: overrides.videoCatalog ?? new SqlitePlaylistVideoCatalog(),
  };
}

function toPlaylistResult<T>(
  result:
    | AddVideoToPlaylistUseCaseResult
    | CreatePlaylistUseCaseResult
    | DeletePlaylistUseCaseResult
    | FindPlaylistsUseCaseResult
    | GetPlaylistDetailsUseCaseResult
    | RemoveVideoFromPlaylistUseCaseResult
    | ReorderPlaylistItemsUseCaseResult
    | UpdatePlaylistUseCaseResult,
): PlaylistResult<T> {
  if (result.ok) {
    return ok(result.data as T);
  }

  switch (result.reason) {
    case 'VALIDATION_ERROR':
      return fail(result.reason, result.message, 400);
    case 'PLAYLIST_NOT_FOUND':
      return fail(result.reason, result.message, 404);
    case 'PLAYLIST_PERMISSION_DENIED':
      return fail(result.reason, result.message, 403);
    case 'DUPLICATE_PLAYLIST_NAME':
    case 'DUPLICATE_VIDEO_IN_PLAYLIST':
      return fail(result.reason, result.message, 409);
    case 'INVALID_PLAYLIST_DATA':
    case 'INVALID_PLAYLIST_POSITION':
    case 'INVALID_SERIES_METADATA':
    case 'PLAYLIST_REORDER_ERROR':
    case 'VIDEO_NOT_FOUND':
      return fail(result.reason, result.message, 400);
    case 'PLAYLIST_QUERY_UNAVAILABLE':
      return fail(result.reason, result.message, 503);
    case 'VIDEO_NOT_FOUND_IN_PLAYLIST':
      return fail(result.reason, result.message, 404);
    case 'PLAYLIST_MUTATION_FAILED':
      return fail(result.reason, result.message, 500);
  }
}

export function createServerPlaylistServices(
  overrides: Partial<ServerPlaylistServiceDependencies> = {},
): ServerPlaylistServices {
  const deps = resolveDependencies(overrides);
  const addVideoToPlaylist = new AddVideoToPlaylistUseCase({
    playlistRepository: deps.playlistRepository,
    videoCatalog: deps.videoCatalog,
  });
  const createPlaylist = new CreatePlaylistUseCase({
    playlistRepository: deps.playlistRepository,
    videoCatalog: deps.videoCatalog,
  });
  const deletePlaylist = new DeletePlaylistUseCase({
    playlistRepository: deps.playlistRepository,
  });
  const findPlaylists = new FindPlaylistsUseCase({
    playlistRepository: deps.playlistRepository,
    videoCatalog: deps.videoCatalog,
  });
  const getPlaylistDetails = new GetPlaylistDetailsUseCase({
    playlistRepository: deps.playlistRepository,
    videoCatalog: deps.videoCatalog,
  });
  const removeVideoFromPlaylist = new RemoveVideoFromPlaylistUseCase({
    playlistRepository: deps.playlistRepository,
  });
  const reorderPlaylistItems = new ReorderPlaylistItemsUseCase({
    playlistRepository: deps.playlistRepository,
  });
  const updatePlaylist = new UpdatePlaylistUseCase({
    playlistRepository: deps.playlistRepository,
  });

  return {
    addVideoToPlaylist: {
      execute: async (input: {
        episodeMetadata?: Record<string, unknown>;
        ownerId: string;
        playlistId: string;
        position?: number;
        videoId: string;
      }): Promise<PlaylistResult<{
        finalPosition: number;
        message: string;
        playlistName: string;
        success: true;
        totalVideosInPlaylist: number;
        videoTitle: string;
      }>> => {
        const result = await addVideoToPlaylist.execute(input);

        if (result.ok) {
          return ok(withSuccessFlag(result.data));
        }

        return toPlaylistResult(result);
      },
    },
    createPlaylist: {
      execute: async (input: CreatePlaylistRequest & { ownerId: string }) => {
        return toPlaylistResult(await createPlaylist.execute(input));
      },
    },
    deletePlaylist: {
      execute: async (input: {
        force?: boolean;
        ownerId: string;
        playlistId: string;
      }): Promise<PlaylistResult<{
        deletedPlaylistName: string;
        message: string;
        relatedPlaylistsAffected: string[];
        success: true;
        videosAffected: number;
      }>> => {
        const result = await deletePlaylist.execute(input);

        if (result.ok) {
          return ok(withSuccessFlag(result.data));
        }

        return toPlaylistResult(result);
      },
    },
    findPlaylists: {
      execute: async (input: FindPlaylistsInput) => toPlaylistResult(await findPlaylists.execute(input)),
    },
    getPlaylistDetails: {
      execute: async (input: GetPlaylistDetailsInput) => toPlaylistResult(await getPlaylistDetails.execute(input)),
    },
    removeVideoFromPlaylist: {
      execute: async (input: {
        ownerId: string;
        playlistId: string;
        videoId: string;
      }): Promise<PlaylistResult<{
        message: string;
        playlistId: string;
        remainingVideos: number;
        success: true;
        videoId: string;
      }>> => {
        const result = await removeVideoFromPlaylist.execute(input);

        if (result.ok) {
          return ok(withSuccessFlag(result.data));
        }

        return toPlaylistResult(result);
      },
    },
    reorderPlaylistItems: {
      execute: async (input: {
        newOrder: string[];
        ownerId: string;
        preserveMetadata?: boolean;
        playlistId: string;
      }): Promise<PlaylistResult<{
        message: string;
        newOrder: string[];
        oldOrder: string[];
        playlistName: string;
        success: true;
        videosReordered: number;
      }>> => {
        const result = await reorderPlaylistItems.execute(input);

        if (result.ok) {
          return ok(withSuccessFlag(result.data));
        }

        return toPlaylistResult(result);
      },
    },
    updatePlaylist: {
      execute: async (input: UpdatePlaylistRequest & {
        ownerId: string;
        playlistId: string;
      }): Promise<PlaylistResult<{
        fieldsUpdated: string[];
        message: string;
        playlist: Playlist;
      }>> => {
        return toPlaylistResult(await updatePlaylist.execute(input));
      },
    },
  };
}

let cachedPlaylistServices: ServerPlaylistServices | null = null;

export function getServerPlaylistServices(): ServerPlaylistServices {
  if (!cachedPlaylistServices) {
    cachedPlaylistServices = createServerPlaylistServices();
  }

  return cachedPlaylistServices;
}
